//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.pro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphane_projesiEntities : DbContext
    {
        public kutuphane_projesiEntities()
            : base("name=kutuphane_projesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_EmanetKitaplar> Tbl_EmanetKitaplar { get; set; }
        public virtual DbSet<Tbl_İade> Tbl_İade { get; set; }
        public virtual DbSet<Tbl_Kayip_kitap> Tbl_Kayip_kitap { get; set; }
        public virtual DbSet<Tbl_Kayitlar> Tbl_Kayitlar { get; set; }
        public virtual DbSet<Tbl_Kitaplar> Tbl_Kitaplar { get; set; }
        public virtual DbSet<Tbl_personel> Tbl_personel { get; set; }
        public virtual DbSet<Tbl_Uyeler> Tbl_Uyeler { get; set; }
    }
}
