//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kayitlar
    {
        public short ID { get; set; }
        public Nullable<short> KitapID { get; set; }
        public Nullable<short> PersonelID { get; set; }
        public Nullable<short> UyeID { get; set; }
        public Nullable<short> EmanetID { get; set; }
        public Nullable<short> İadeID { get; set; }
        public Nullable<short> KayipID { get; set; }
    
        public virtual Tbl_EmanetKitaplar Tbl_EmanetKitaplar { get; set; }
        public virtual Tbl_İade Tbl_İade { get; set; }
        public virtual Tbl_Kayip_kitap Tbl_Kayip_kitap { get; set; }
        public virtual Tbl_Kitaplar Tbl_Kitaplar { get; set; }
        public virtual Tbl_personel Tbl_personel { get; set; }
        public virtual Tbl_Uyeler Tbl_Uyeler { get; set; }
    }
}
