//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_İade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_İade()
        {
            this.Tbl_Kayitlar = new HashSet<Tbl_Kayitlar>();
        }
    
        public short İadeID { get; set; }
        public string İadeTC { get; set; }
        public string İadeAdSoyad { get; set; }
        public string İadeYas { get; set; }
        public string İadeTelefon { get; set; }
        public string İadeKBarkod { get; set; }
        public string İadeKAd { get; set; }
        public string İadeKYazar { get; set; }
        public Nullable<int> İadeKSayi { get; set; }
        public string İadeKTeslim { get; set; }
        public string İadeKreturnTarih { get; set; }
        public string personel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kayitlar> Tbl_Kayitlar { get; set; }
    }
}
