//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kayip_kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kayip_kitap()
        {
            this.Tbl_Kayitlar = new HashSet<Tbl_Kayitlar>();
        }
    
        public short KayipID { get; set; }
        public string KayipTC { get; set; }
        public string KayipAdSoyad { get; set; }
        public string KayipYas { get; set; }
        public string KayipTelefon { get; set; }
        public string KayipBarkod { get; set; }
        public string Kitaplar { get; set; }
        public string KayipKYazar { get; set; }
        public Nullable<int> KayipKSayi { get; set; }
        public string KayipTeslimTarih { get; set; }
        public string KayipİadeTarih { get; set; }
        public string KayipTeslimPer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kayitlar> Tbl_Kayitlar { get; set; }
    }
}
