//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Uyeler()
        {
            this.Tbl_Kayitlar = new HashSet<Tbl_Kayitlar>();
        }
    
        public short UyeID { get; set; }
        public string UyeTC { get; set; }
        public string UyeAd { get; set; }
        public string UyeSoyad { get; set; }
        public string UyeCinsiyet { get; set; }
        public string UyeDogumtarih { get; set; }
        public string UyeTelefon { get; set; }
        public string UyeEposta { get; set; }
        public string UyeSifre { get; set; }
        public string UyeAdres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kayitlar> Tbl_Kayitlar { get; set; }
    }
}
